services:
  - type: web
    name: fastapi-chat-app
    env: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry install
    startCommand: |
      poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
